spring:
  application:
    name: micro-Book
  datasource:
    url: jdbc:mysql://localhost:3306/my_book_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always